# Generated by Django 4.2.6 on 2023-10-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
